apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- services.yaml

namespace: goapp

images:
- name: goapp
  newName: joaofstn323/teste-app-argocd
  newTag: b2de84b48391b3a6736668c3260c620e12e66d07
