name: CD
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  publish_image:
    runs-on: ubuntu-latest
    name: Build and Deploy Dockerhub
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build -t joaofstn323/teste-app-argocd:${{ github.sha }} .
      - name: push docker hub
        run: |
          docker login -u joaofstn323 -p ${{ secrets.DOCKER_PASSWORD }}
          docker push joaofstn323/teste-app-argocd:${{ github.sha }}
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: publish_image
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1
      
      - name: update k8s
        run: |
          cd k8s
          kustomize edit set image goapp=joaofstn323/teste-app-argocd:${{ github.sha }}
          cat kustomization.yaml

      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "change image tag"

      - name: push
        uses: ad-m/github-push-action@master